### ISSUE TITLE
MikroTik Devices

### ISSUE THREAD

**Issue by grego1981** [fusioninventory/sysobject.ids#12]
Hello, 

I have several Mikrotik devices in my Network and would be helpful to have them inventoried and discovered by FI.

Attached the latest MIB file if it helps.

Thank you!

[Mikrotik.zip](https://github.com/fusioninventory/sysobject.ids/files/1634217/Mikrotik.zip)

**Comment by g-bougard** [comment]
HI @grego1981 

thank you for the MIB file, it is more recent the the one I still have. This can help, but what we need is the result of:
```
snmpget -v2c -c public "serverIP" 1.3.6.1.2.1.1.2.0
```
where you set "serverIP" to related devices in your environment. If you have many different models, you should provide a list of the snmpget result with corresponding expected model. The mib will help if models are also found there.

**Comment by grego1981** [comment]
snmpget -v2c -c public 10.0.0.3 1.3.6.1.2.1.1.2.0
SNMPv2-SMI::mib-2.1.2.0 = OID: MIKROTIK-MIB::mikrotikExperimentalModule

snmpget -v2c -c public 10.5.0.1 1.3.6.1.2.1.1.2.0
SNMPv2-SMI::mib-2.1.2.0 = OID: MIKROTIK-MIB::mikrotikExperimentalModule


This is from 2 different Mikrotik Router Models, The output containing the model from SnmpB application is 91: sysDescr.0 RouterOS RB1100x4 for the first router
and 129: sysDescr.0 RouterOS CRS125-24G-1S for the second one

**Comment by g-bougard** [comment]
I should have close this issue after df0d4b3d659a8c522ced06a77e7ea4075f50180d was pushed.
