### ISSUE TITLE
Fortigate Updates for E models

### ISSUE THREAD

**Issue by wnoisephx** [fusioninventory/sysobject.ids#17]
#  Fortigate Virtual Models
12356.101.1.41  Fortinet        NETWORKING      FortiOS VM64 XEN
12356.101.1.47  Fortinet        NETWORKING      Fortigate VM64 OPC
12356.101.1.61  Fortinet        NETWORKING      Fortigate VM64 NPU
12356.101.1.65  Fortinet        NETWORKING      Fortigate VM64 GCP

# Fortigate E Models
12356.101.1.306 Fortinet        NETWORKING      Fortigate 30E
12356.101.1.505 Fortinet        NETWORKING      Fortigate 50E
12356.101.1.515 Fortinet        NETWORKING      Fortigate 51E
12356.101.1.518 Fortinet        NETWORKING      Fortigate 52E
12356.101.1.641 Fortinet        NETWORKING      Fortigate 60E
12356.101.1.640 Fortinet        NETWORKING      Fortigate 61E
12356.101.1.842 Fortinet        NETWORKING      Fortigate 80E
12356.101.1.843 Fortinet        NETWORKING      Fortigate 81E
12356.101.1.844 Fortinet        NETWORKING      Fortigate 80E POE
12356.101.1.940 Fortinet        NETWORKING      Fortigate 90E
12356.101.1.941 Fortinet        NETWORKING      Fortigate 91E
12356.101.1.1041 Fortinet        NETWORKING      Fortigate 100E
12356.101.1.1043 Fortinet        NETWORKING      Fortigate 101E
12356.101.1.1005 Fortinet        NETWORKING      Fortigate 140E
12356.101.1.2009 Fortinet        NETWORKING      Fortigate 200E
12356.101.1.2010 Fortinet        NETWORKING      Fortigate 201E
12356.101.1.3007 Fortinet        NETWORKING      Fortigate 300E
12356.101.1.3008 Fortinet        NETWORKING      Fortigate 301E
12356.101.1.5005 Fortinet        NETWORKING      Fortigate 500E
12356.101.1.5006 Fortinet        NETWORKING      Fortigate 501E
12356.101.1.20000 Fortinet        NETWORKING      Fortigate 2000E
12356.101.1.25000 Fortinet        NETWORKING      Fortigate 2500E
12356.101.1.39601 Fortinet        NETWORKING      Fortigate 3960E
12356.101.1.39801 Fortinet        NETWORKING      Fortigate 3980E
12356.101.1.50016 Fortinet        NETWORKING      Fortigate 5001E
12356.101.1.50017 Fortinet        NETWORKING      Fortigate 5001E1

# FortiWiFi E Models
12356.101.1.316 Fortinet        NETWORKING      FortiWiFi 30E
12356.101.1.506 Fortinet        NETWORKING      FortiWiFi 50E
12356.101.1.516 Fortinet        NETWORKING      FortiWiFi 51E
12356.101.1.639 Fortinet        NETWORKING      FortiWiFi 60E
12356.101.1.649 Fortinet        NETWORKING      FortiWiFi 61E

**Comment by g-bougard** [comment]
Hi @wnoisephx 

thank you for this submission. Most are really new, few was still correctly defined but actually we have 2 that are conflicting with your list:
```
12356.101.1.1005	Fortinet	NETWORKING	Fortigate 140E
12356.101.1.20000	Fortinet	NETWORKING	Fortigate 2000E
```
Can you explain why we should trust your definition ? Have you some related snmpwalk to submit ?
Best regards

**Comment by g-bougard** [comment]
Here is exactly the conflict.
Your proposition:
```
12356.101.1.1005	Fortinet	NETWORKING	Fortigate 140E
12356.101.1.20000	Fortinet	NETWORKING	Fortigate 2000E
```
What we have:
```
12356.101.1.1005	Fortinet	NETWORKING	Fortigate 100C
12356.101.1.20000	Fortinet	NETWORKING	Fortigate 2000
```

**Comment by wnoisephx** [comment]
I've taken my information directly from fortinet's snmp mib for the fortigates.

Here is the line for the 2000E - from the 6.0.1 firmware version of the mib dated 2018-06-05 16:06:41
fgt2000E         OBJECT IDENTIFIER ::= { fgModel 20000 }

Just as check I also downloaded the mib from 5.0.9 firmware version of the mib dated 2014-08-01 13:08:10 which would have covered all the way back to the A models.   And there is no reference to the 2000 model at all 
here is their hardware manual page which shows most of the models 
https://docs.fortinet.com/fortigate/hardware 
also searching the web shows that the first version of the fortigate 2000 was the E model.   I did find other fortinet 2000 products (most notably the FortiAnalyzer)


As for the 140 models Fortinet did something weird here.   Here are the lines from the 6.0.1 firmware
fgt140D          OBJECT IDENTIFIER ::= { fgModel 1401 }
fgt140E          OBJECT IDENTIFIER ::= { fgModel 1005 }
fgt140EP         OBJECT IDENTIFIER ::= { fgModel 1006 }
fgt140P          OBJECT IDENTIFIER ::= { fgModel 1402 }

here is the line from the 5.0.9 firmware
fr100C           OBJECT IDENTIFIER ::= { fgModel 1005 }
So they reused the number?   I don't know if that is a mistake, because I would have though that the 140 models should have started with 140 (like the others)
I don't have the hardware, but I could call their support line and open a ticket with them just to see which is write.

My suggestion would be update the 2000, and wait until I can file a support ticket with fortinet about the 140 models.

**Comment by g-bougard** [comment]
Hi @wnoisephx 
thank you for the detailed informations.
I just updated as you suggested the 2000E entry.
For the 100C/140E, I suppose 100C was a mistake from Fortinet. But it would be great if you have a confirmation from them.
Regarding the 140 models you're showing, it seems we still can add one other entry for the 140EP...

**Comment by wnoisephx** [comment]
I’m going to open a case with Fortinet about  the 100C/140E issue
As for the 140EP that seems to be the 140E POE version…

**Comment by dsctechs** [comment]
I opened a case with fortinet and had them pull the id's from running systems.   Here is their response

Hello,
Thank you for waiting for the response. I enumerated our MIB file and tested the FGATE model values:
100D:
.1.3.6.1.4.1.12356.101.1.1004
100E:
.1.3.6.1.4.1.12356.101.1.1041
101E
.1.3.6.1.4.1.12356.101.1.1043
140D:
.1.3.6.1.4.1.12356.101.1.1401
140E:
.1.3.6.1.4.1.12356.101.1.1005
140EP:
.1.3.6.1.4.1.12356.101.1.1006
140P:
.1.3.6.1.4.1.12356.101.1.1402

This appears to match the values you're seeing. So it appears those values are correct from our Publicly available MIB files. As indicated, we update MIBs and values for each new release of FortiOS. It's not uncommon for values to see updates or changes.

I hope this answers your questions!

**Comment by g-bougard** [comment]
Hi @dsctechs 
thank you for the feedback.
I'm updating the list with that information.
I'm still suspicious about one point, Fortigate 100C is no more indexed. If anyone has such a model it should report an issue if it now appears as a Fortigate 140E.
