### ISSUE TITLE
Please add VOIP Phone to the support list 

### ISSUE THREAD

**Issue by tianmucn** [fusioninventory/sysobject.ids#18]
VOIP Phone - SNOM support SNMP ,But Can not discover by Fusioninventory. Please help to add it 
reference link : http://wiki.snom.com/Category:HowTo:SNMP. Thanks

**Comment by g-bougard** [comment]
Hi @tianmucn 
this may be possible if you of course enable SNMP on the phone (I assume you do). But then, the link you propose doesn't show the default OID we inspect.
Could you provide us a [snom snmpwalk output](http://fusioninventory.org/documentation/bugreport/#snmpwalk-output) so we can check how to do that part and test on our side ?

**Comment by g-bougard** [comment]
Hi @tianmucn 
without any answer I'm closing this issue.
If you just missed my first comment and finally can provide the snmpwalk output, feel free to reopen.
Thank you.
