### ISSUE TITLE
Epson Printer AL-M400 and BX320

### ISSUE THREAD

**Issue by Efe16** [fusioninventory/sysobject.ids#2]
For the Epson Printers AL-M4000 and BX320, I add this 

 .1.3.6.1.4.1.1248.1.2.2.1.1.1.2.1                                               Epson   PRINTER              AL-M400
 .1.3.6.1.4.1.1248.1.2.2.1.1.1.2.1                                               Epson   Stylus OfficeBX525WD-66FFF5

**Comment by g-bougard** [comment]
Hi @Efe16 
sorry for the delay, but can you check the just updated [README Contribution section](https://github.com/fusioninventory/sysobject.ids/blob/master/README.md) as we need the real SysObjectId variable content ?
The values you're providing are identical and seems not to be coherent with currently supported Epson devices.
Thank you in advance

**Comment by g-bougard** [comment]
Hi @Efe16 

without response, I'm closing the issue.

If you finally have an answer to my previous comment, don't hesitate to re-open the issue and complete it.

Thank you
