### ISSUE TITLE
query using fusioninventory-netinventory and SNMPv3 

### ISSUE THREAD

**Issue by Wolvverine** [fusioninventory/sysobject.ids#25]
Specifying how to query using fusioninventory-netinventory and SNMPv3 would also be helpful (neither help nor documentation describes this).

from code:
--credentials  version:3,username:admin,authprotocol:sha,authpassword:'s3cr3t',privpassword:'ttge674f',

**Comment by g-bougard** [comment]
This is not a sysobject.ids issue and you still opened it in fusioninventory-agent issues.
Closing so.

**Comment by guillomovitch** [comment]
> Specifying how to query using fusioninventory-netinventory and SNMPv3 would also be helpful (neither help nor documentation describes this).
You'd rather look better: see 2nd example in EXAMPLES section of man page, or lines 318 to 322 here: https://github.com/fusioninventory/fusioninventory-agent/blob/develop/bin/fusioninventory-netinventory

**Comment by Wolvverine** [comment]
https://github.com/fusioninventory/fusioninventory-agent/issues/565#issuecomment-426015953
