### ISSUE TITLE
OID for HP Pro Liant servers

### ISSUE THREAD

**Issue by nick888999** [fusioninventory/sysobject.ids#3]
Please add OIDs for HP Pro Liant servers to sysobject.ids
Tried the following ones, but the don't work with fusioninventory-agent:
232
232.2.2.2.1.0
232.2.2.4.2.0

**Comment by guillomovitch** [comment]
First, we need the corresponding models.

Second, what do you mean by "they don't work", and why should we add them if they don't work ?

**Comment by nick888999** [comment]
Please find below the following HP server models:
ProLiant DL360 G5
ProLiant DL360p Gen8
ProLiant DL380e Gen8

For instance, I checked by snmpget and it grubs SN for the server, but fusioninventory agent can't.
root@38b131511df4 /]# snmpget -v2c -c public "serverIP" 1.3.6.1.4.1.232.2.2.2.1.0
SNMPv2-SMI::enterprises.232.2.2.2.1.0 = STRING: "CZJ916A15L      "

Any ideas?

**Comment by guillomovitch** [comment]
You are misinterpreting the purpose of the sysobject.ids file. It doesn't contain information about how to retrieve a string value that would identify the model, but how to interpret the value that we already know to retrieve, the SysObjectID variable (1.3.6.1.2.1.1.2), which happens to be an OID itself.

Just try the following command to understand:
<pre>
# snmpget -v2c -c public "serverIP" 1.3.6.1.2.1.1.2.0
</pre>

Or the following one, to see how the agent uses this information:
<pre>
# fusioninventory-netinventory --credentials version:2c,community:public --debug "serverIP"
</pre>

If those models are unknown, you have to add additional mappings in the sysobject.ids file, using expected syntax.

**Comment by g-bougard** [comment]
Hi @nick888999 

have you try to retrieve the the sysObjectID variable as suggested by @guillomovitch ?

Finally you may prefer to install [fusioninventory-agent](/fusioninventory/fusioninventory-agent.git) so you will obtain a better computer inventory. This is really the purpose of the agent.

**Comment by g-bougard** [comment]
Hi @nick888999 

I merged today a PR in agent code which could help to handle such case and get rid of sysobject.ids support need. Btw I need some snmp walks to implement this support. At the moment I even added iLo card detection. Do you think you can provide us snmp walks for these computers ? See [snmpwalk output in our documentation](http://fusioninventory.org/documentation/bugreport/#snmpwalk-output).

**Comment by g-bougard** [comment]
Hi @nick888999 
I'm closing this without your feedback.
Feel free to re-open.
