### ISSUE TITLE
NAS QNAP wrong type : networkEquipement instead of computer

### ISSUE THREAD

**Issue by 1Fopresta** [fusioninventory/sysobject.ids#33]
Fusion import the NAS like a network equipement :  [itemtype]:NetworkEquipment

Here the MIB for the TS-639 model : ~~http:// dl.free.fr /kb8aeAKLW~~

Same problem with TS-419P+ and TS-239 Pro II

**Comment by g-bougard** [comment]
Hi @1Fopresta 
the MIB may help, but your url is broken at the moment, probably expired in dl.free.fr.
Btw we would better benefit from full [snmpwalk ouitputs](http://fusioninventory.org/documentation/bugreport/#snmpwalk-output) for each model so we can directly test the result.
Can you provide some snmpwalks for the models you own then ?

**Comment by g-bougard** [comment]
Closing without any snmp walk submission.
Feel free to submit the walk into a [new fusioninventory-agent issue](https://github.com/fusioninventory/fusioninventory-agent/issues) is you finally manage to create one.
