### ISSUE TITLE
KEMP Loadbalancer

### ISSUE THREAD

**Issue by Wolvverine** [fusioninventory/sysobject.ids#34]
[KEMP.snmp.txt](https://github.com/fusioninventory/sysobject.ids/files/2764656/KEMP.snmp.txt)

**Comment by g-bougard** [comment]
Hi @Wolvverine 

thank you for this snmpwalk submission.

Can you please answer to the following questions:
1. Is the manufacturer "KEMP Technologies" ? or Do you think "KEMP" is enough ?
2. About the model, is "Loadmaster" sufficient in your point of view ?
3. Agent doesn't find any MAC, but looking at the walk I see there are maybe `00:50:56:90:59:bb` & `00:50:56:90:4f:c2`, can you confirm ?
4. Have you a serial number which we can search for in the walk ?

**Comment by Wolvverine** [comment]
1. KEMP Technologies
2. yes
3. Yes.
