### ISSUE TITLE
PDU - Smart-UPS RT 6000 RM XL

### ISSUE THREAD

**Issue by robsonjorgefernandez** [fusioninventory/sysobject.ids#35]
Hi,

Is it possible to add the *PDU Smart-UPS RT 6000 RM XL* to sysobject.ids?

```
snmpwalk -v 2c -c public -t 15 -Cc -On -Ox pdu01 .1 > Smart-UPS_RT_6000_RM_XL.txt
```
Output: [Smart-UPS_RT_6000_RM_XL.txt](https://github.com/fusioninventory/sysobject.ids/files/2851468/Smart-UPS_RT_6000_RM_XL.txt)

MIB: [powernet417.txt](https://github.com/fusioninventory/sysobject.ids/files/2851470/powernet417.txt)

Best regards.

**Comment by g-bougard** [comment]
Hi @robsonjorgefernandez 
the PDU Smart-UPS RT 6000 RM XL was still added to the file 2 years ago.
I tried your walk and it seems we don't recognize the serial number. Can you tell us what is the serial number so we can check which OID should provide it ? Then we will be able to enhance the APC support.

**Comment by robsonjorgefernandez** [comment]
Hi @g-bougard 

Follow the serial number below:

```
# snmpwalk -v 2c -c public pdu01 PowerNet-MIB::upsAdvIdentSerialNumber
PowerNet-MIB::upsAdvIdentSerialNumber.0 = STRING: "QS1231150376"
```
PDU
![image](https://user-images.githubusercontent.com/16673533/55967102-19b5e180-5c50-11e9-85e6-0ddf752b0baa.png)

UPS Network Management Card 2
![image](https://user-images.githubusercontent.com/16673533/55967059-030f8a80-5c50-11e9-83af-3116ad5e8fb4.png)
Best regards,

**Comment by g-bougard** [comment]
Thank you,
I just added the S/N support in [b7484dbd](https://github.com/fusioninventory/fusioninventory-agent/commit/b7484dbd74b4c78c107dd33994aef97cc1b7df0e)
