### ISSUE TITLE
Add Dell Enterprise support

### ISSUE THREAD

**Issue by szilvasidave** [fusioninventory/sysobject.ids#36]
Hi,

would it be possible to add support for Dell Poweredge and Enterprise products?
MIBs can be downloaded from https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=37gwd

PowerEdge servers have 
OID=.1.3.6.1.2.1.1.2.0
Value=1.3.6.1.4.1.674.10892.5

Let me know if you need more information

**Comment by g-bougard** [comment]
Hi @szilvasidave 
can you also provide some [snmpwalk outputs](http://fusioninventory.org/documentation/bugreport/#snmpwalk-output) so we can validate and eventually enhance this support ?
