### ISSUE TITLE
Riverbed Xirrus Access Points MIB SNMP file

### ISSUE THREAD

**Issue by crespicarlos** [fusioninventory/sysobject.ids#39]
Hello, I would like to provide you with the MIB file to add the Xirrus APs to the fusioninventory database:

https://riverbed--c.na57.content.force.com/servlet/servlet.EmailAttachmentDownload?q=38cim9H8Cjm%2F0gFVbVzYffqbT7fj4bCiSGXH9kDcDsKxaIOGIz7lnESTWgRU02IVvJlw3cezhQgxTlFXN0TaXg%3D%3D

**Comment by guillomovitch** [comment]
Thanks, but we don't manually review vendors MIBS to identify model identifiers. If you want Xirrus APs added to the agent database, please provide the relevant sysobjectid/model mappings, as documented [here](http://fusioninventory.org/documentation/agent/database).

**Comment by g-bougard** [comment]
Also a full [snmpwalk output](http://fusioninventory.org/documentation/bugreport/#snmpwalk-output) can do the job ?

**Comment by crespicarlos** [comment]
I have added the following devices:
47196	Hewlett-Packard	NETWORKING
47196.4.1.1.1.2	Hewlett-Packard	NETWORKING	Aruba 8320-48G-SFP+
21013	Xirrus	NETWORKING
21013.1.153	Xirrus	NETWORKING	XR620
21013.1.157 Xirrus	NETWORKING	XR2436
21013.1.236	Xirrus	NETWORKING	XD2-230
21013.1.188	Xirrus	NETWORKING	XD4-130

Is that enough?
I have the client on a Windows server and I can't run snmpwalk output easily.

**Comment by g-bougard** [comment]
Hi @crespicarlos 
Yes this should be enought.
If you still modified your sysobject.ids to enhance your network inventory, you probably would have to directly "edit" [sysobject.ids in github](https://github.com/fusioninventory/sysobject.ids/blob/master/sysobject.ids) as, in that case, a PR is just faster for us to integrate than an issue.

**Comment by g-bougard** [comment]
In your list, `21013.1.157	Xirrus	NETWORKING	XR2436` had a space between the OID part and the manufacturer. Check your sysobject.ids in the case you did the mistake there. In that case, you'll obtain "partial match" for this device and the model may finally be wrong.

I added "Aruba 8400" as I quickly find a reference for this OID too, but without the full model. So maybe the model for Aruba 8320 can be different than yours.
