### ISSUE TITLE
Add some switches

### ISSUE THREAD

**Issue by crespicarlos** [fusioninventory/sysobject.ids#40]
207.1.4.145	Allied Telesyn	NETWORKING	AT-8000-GS/48-50
171.10.76.5	D-Link	NETWORKING	DGS-1224T
171.10.127.1	D-Link	NETWORKING	DXS-3600-32S

Thanks, great job!

**Comment by FernandoJungblut** [comment]
11.2.3.7.11.183 Hewlett-Packard NETWORKING JL380A HPE 1920S 8G Switch
11.2.3.7.11.184 Hewlett-Packard NETWORKING JL381A HPE 1920S 24G Switch
11.2.3.7.11.185 Hewlett-Packard NETWORKING JL382A HPE 1920S 48G Switch
11.2.3.7.11.186 Hewlett-Packard NETWORKING JL383A HPE 1920S 8G PPoE+ (65W) Switch
11.2.3.7.11.187 Hewlett-Packard NETWORKING JL384A HPE 1920S 24G PPoE+ (185W) Switch
11.2.3.7.11.188 Hewlett-Packard NETWORKING JL385A HPE 1920S 24G PPoE+ (370W) Switch
11.2.3.7.11.198 Hewlett-Packard NETWORKING JL386A HPE 1920S 48G PPoE+ (370W) Switch


[Font](https://shop.bechtle.pl/medias/7mfJgcxSkKBip46jCBYV58-30.pdf)
