### ISSUE TITLE
Addition of Teradici Zero client

### ISSUE THREAD

**Issue by davebez80** [fusioninventory/sysobject.ids#46]
Please see attached snmpwalk of device in question. Thanks

[snmpCapture.txt](https://github.com/fusioninventory/sysobject.ids/files/3838664/snmpCapture.txt)

**Comment by g-bougard** [comment]
Hi @davebez80 
I added the needed entries,  btw this not means the Teradici Zero CLient support is complete.
Please, open an issue on the [agent github](https://github.com/fusioninventory/fusioninventory-agent/issues) pointing this issue and giving at least the S/N of the the device to find in the walk you provided.
