### ISSUE TITLE
Microsoft MIB

### ISSUE THREAD

**Issue by walterdasilva** [fusioninventory/sysobject.ids#49]
Does it make sense to include more information for mib microsoft like this?

windowsNT | 1.3.6.1.4.1.311.1.1.3.1
-- | --
workstation | 1.3.6.1.4.1.311.1.1.3.1.1
server | 1.3.6.1.4.1.311.1.1.3.1.2
dc | 1.3.6.1.4.1.311.1.1.3.1.3

Thanks

**Comment by g-bougard** [comment]
Hi @walterdasilva 
no it doesn't make sens as computers are not supported by the NetInventory task.
