### ISSUE TITLE
HP Designjet T120

### ISSUE THREAD

**Issue by danielcousosouto** [fusioninventory/sysobject.ids#57]
Hi,
Is it possible to add this printer?
iso.3.6.1.2.1.1.2.0 = OID: joint-iso-ccitt.2826942304.808466785.929442864.1664101424.1697656880.808464432.808464432

HP Designjet T120

Please ask for more information if needed.

Thanks

[HP T120.txt](https://github.com/fusioninventory/sysobject.ids/files/5836230/HP.T120.txt)

**Comment by g-bougard** [comment]
Hi @danielcousosouto 
it seems your inventory is okay. Do you mean you had to insert an entry in your sysobject.ids to obtain it ? If yes, please, can you show you sysobjectid.ids entry ?

**Comment by danielcousosouto** [comment]
There was only a printer without import, It was a fault in the rule. I'm sorry and thank you very much.
