### ISSUE TITLE
new items

### ISSUE THREAD

**Issue by we-sell-bags** [fusioninventory/sysobject.ids#59]
all snmpget -v2c -c  172.18.0.23 1.3.6.1.2.1.1.2.0

Sonicwall NSA 2600
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.8741.1

Ruckus
zoneDirector 1200
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.25053.3.1.5.15

ruckus AP R500
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.25053.3.1.4.71

Synology RS18017xs+

SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10

**Comment by we-sell-bags** [comment]
if i get a complete device walk is that ok?
the info is in there , it just seems it's not in the areas you would expect

**Comment by g-bougard** [comment]
Hi,
you can provide walks privately, by email or telegram for example, if you trust us to not use them for anything else than develop the expected support.
Such provided walks are also stored in a private repository so we can test easily updates.
Anyway you still have to open an issue on the agent GH issues as explained earlier.

**Comment by we-sell-bags** [comment]
Hi,
Which email address?

**Comment by we-sell-bags** [comment]
which email?

**Comment by g-bougard** [comment]
As I said you still first have to open an issue for the agent. And indeed you'll find my professional mail in [the related repository README](https://github.com/fusioninventory/fusioninventory-agent), a mail finishing by teclib.com.

**Comment by g-bougard** [comment]
Closing as issues has been opened on agent side
