### ISSUE TITLE
Dell Wyse with FusionInventory 

### ISSUE THREAD

**Issue by smarcos-starxpert** [fusioninventory/sysobject.ids#63]
Hi,

I'm trying to inventory Wyse devices on FusionInventory 2.6 & GLPI 9.5.3
I tried NetDiscovery, but it seems to be found as printers.
Then, it inventorize only few information that aren't realy reliable : 

- Name
- Manufacture 
- Sysdescr
- Internet (port and network) 

Does anyone knows if it's possible to fully inventory Dell Wyse devices (known as light devices with ThinOS installed) as if we installed FusionInventory agent in it ?

The thing is that we can't inventory and do not have to serial number as, for example : 

Name/OID: .1.3.6.1.4.1.714.1.2.6.2.1.0; Value (OctetString): 651A4C6JV72 (is the serial number)

Regards

**Comment by smarcos-starxpert** [comment]
More information :
snmpget -v1 -c ******* "192.168.10.102" .1.3.6.1.4.1.714.1.2.6.2.1.0
iso.3.6.1.4.1.714.1.2.6.2.1.0 = STRING: "651A4C6JV72"

------------------

snmpget -v1 -c ************* "192.168.10.102" .1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.714.1.2.6

**Comment by smarcos-starxpert** [comment]
root@vm-glpi-prod:~# fusioninventory-netinventory --credentials version:1,community:******** --debug --host "192.168.10.102"
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: 192.168.10.102
[debug] [thread 1] #1, partial match for sysobjectID .1.3.6.1.4.1.714.1.2.6 in database: unknown device ID
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <INFO>
        <COMMENTS>3012-T10D  8.5_017</COMMENTS>
        <ID>0</ID>
        <IPS>
          <IP>127.0.0.1</IP>
          <IP>192.168.10.102</IP>
        </IPS>
        <MAC>00:80:64:eb:12:ca</MAC>
        <MANUFACTURER>Wyse</MANUFACTURER>
        <NAME>WT008064eb12ca</NAME>
        <TYPE>PRINTER</TYPE>
        <UPTIME>9 hours, 28:50.02</UPTIME>
      </INFO>
      <PORTS>
        <PORT>
          <IFDESCR>loop0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>16384</IFMTU>
          <IFNAME>loop0</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>0</IFOUTOCTETS>
          <IFSPEED>1</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>24</IFTYPE>
          <IP>127.0.0.1</IP>
          <IPS>
            <IP>127.0.0.1</IP>
          </IPS>
        </PORT>
        <PORT>
        <UPTIME>9 hours, 29:07.98</UPTIME>
      </INFO>
      <PORTS>
        <PORT>
          <IFDESCR>loop0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>16384</IFMTU>
          <IFNAME>loop0</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>0</IFOUTOCTETS>
          <IFSPEED>1</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>24</IFTYPE>
          <IP>127.0.0.1</IP>
          <IPS>
            <IP>127.0.0.1</IP>
          </IPS>
        </PORT>
        <PORT>
          <IFDESCR>enet0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>374487615</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>enet0</IFNAME>
          <IFNUMBER>2</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>717476499</IFOUTOCTETS>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <IP>192.168.10.102</IP>
          <IPS>
            <IP>192.168.10.102</IP>
          </IPS>
          <MAC>00:80:64:eb:12:ca</MAC>
        </PORT>
      </PORTS>
    </DEVICE>
    <MODULEVERSION>4.2</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netinventory threads terminated

**Comment by smarcos-starxpert** [comment]
[fusioninventory-netinventory_command.txt](https://github.com/fusioninventory/sysobject.ids/files/5888691/fusioninventory-netinventory_command.txt)

**Comment by g-bougard** [comment]
Hi @smarcos-starxpert 

indeed we have an entry in sysobject.ids telling:
```
714	Wyse	PRINTER
```
This explains why you see it as PRINTER.

Can you add the following entry in your sysobject.ids ?
```
714.1.2.6	Wyse	NETWORKING	Dell Wyse
```
Be careful to use only one tabulation between each fields.

Anyway, I don't know if "Dell Wyse" is really the model we should set. Maybe another OID is available for. Have you a link toward an official MIB ?

**Comment by smarcos-starxpert** [comment]
Hi to you @g-bougard 

It worked, thanks. They are now in the Network Equipment section.

Now, the thing is that they do not respond to the inventory. They donc give anything but :

- Mac address (enabling the rule otherwise they were denied)
- itemtype is now NetworkEquipment
- Model: Wyse
- Name: the name of the equipment

How to do to get the inventory as if we had installed an agent ?

**Comment by smarcos-starxpert** [comment]
Hi again @g-bougard,

I tried by making understand GLPI & FusionInventory to dig into the netinventory process to gather more information.
However, impossible to get more information than the beggining. Even if it's now considered as a Network Equipment.

**Comment by g-bougard** [comment]
Hi @smarcos-starxpert 

You asked:
> How to do to get the inventory as if we had installed an agent ?

This is not possible with netinventory as computer inventory is not supported by that agent task. And even it won't be as SNMP support is generally not sufficient to produce an inventory computer. The only way is to integrate the agent into the system itself and unless Dell Wyse permits to install some sort of package, there's no simple way. Do you know if packages would be installed and how ?

To continue on the SNMP support, we can develop a dedicated MibSupport agent plugin to support reporting the S/N. It would be nice to identify an OID for the model and the firmware to report the ThinOS version. We may need snmpwalks and if possible related private MIBs to do so.

**Comment by vhribeiro** [comment]
I have the same "question" and i can import into inventory the serial number of dell wyse ive obtain the folloing info:

The serial:
SnmpGet v1.01 - Copyright (C) 2009 SnmpSoft Company
[ More useful network tools on http://www.snmpsoft.com ]

OID=.1.3.6.1.4.1.714.1.2.6.2.1.0
Type=OctetString
Value=JC7QDT2

In fusioninventory than value not apear:

c:\Program Files\FusionInventory-Agent\perl\bin>perl.exe fusioninventory-netinventory --credentials version:1,community:public --debug --host xxx.xxx.xxx.xx
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: xxx.xxx.xxx.xxx
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.714.1.2.6 in database
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <INFO>
        <COMMENTS>3040  8.6_013</COMMENTS>
        <ID>0</ID>
        <IPS>
          <IP>xxx.xxx.xxx.xxx</IP>
          <IP>127.0.0.1</IP>
        </IPS>
        <MAC>6c:2b:59:59:bb:xx</MAC>
        <MANUFACTURER>Dell</MANUFACTURER>
        <MODEL>Dell Wyse</MODEL>
        <NAME>NAME</NAME>
        <TYPE>NETWORKING</TYPE>
        <UPTIME>1 hour, 15:15.07</UPTIME>
      </INFO>
      <PORTS>
        <PORT>
          <IFDESCR>loop0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>16384</IFMTU>
          <IFNAME>loop0</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>0</IFOUTOCTETS>
          <IFSPEED>1</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>24</IFTYPE>
          <IP>127.0.0.1</IP>
          <IPS>
            <IP>127.0.0.1</IP>
          </IPS>
        </PORT>
        <PORT>
          <IFDESCR>enet0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>42224995xx</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>enet0</IFNAME>
          <IFNUMBER>2</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>98692702</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <IP>xxx.xxx.xxx.xxx</IP>
          <IPS>
            <IP>xxx.xxx.xxx.xxx</IP>
          </IPS>
          <MAC>6c:2b:59:59:bb:xx</MAC>
        </PORT>
      </PORTS>
    </DEVICE>
    <MODULEVERSION>4.2</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netinventory threads terminated

How to get the serial imported?

The model and firmware apears in Sysdescr field.


tanks

**Comment by smarcos-starxpert** [comment]
Hi @vhribeiro 

You should have a file like this in your fusion inventory :
fusioninventory/lib/FusionInventory/Agent/SNMP/Device.pm
Inside it you should have a function _getSerial, with a table of oids to try to retrieve the serial.
We then just added the oid for the wyse serial number at the end of the table.

**Comment by g-bougard** [comment]
Hi here,
I just developed a dedicated WyseThinOS mibsupport module for [glpi-agent in a dedicated branch](https://github.com/glpi-project/glpi-agent/blob/feature/dell-wyse-thinclient-support). It is fully compatible with FusionInventory Agent 2.6 so try it if you can. To do so, just download [WyseThinOS.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/feature/dell-wyse-thinclient-support/lib/FusionInventory/Agent/SNMP/MibSupport/WyseThinOS.pm) file and copy it to `FusionInventory/Agent/SNMP/MibSupport` subfolder in your agent installation path. You should also revert any modification in your agent related to Wyse support to validate the dev.

**Comment by TheRoby** [comment]
Hi,
Thank you, i update my agent and start a test :)
ThinOs 9 is out (we use 8.6). i'll try if the snmp have more infos when we test it !

**Comment by TheRoby** [comment]
Hi, it works really well !

Thank you :)

**Comment by g-bougard** [comment]
Thank you for the feed back.
I just merged the branch in glpi-agent default branch.
