### ISSUE TITLE
Invalid device classification (UniFi as computer)

### ISSUE THREAD

**Issue by danielcousosouto** [fusioninventory/sysobject.ids#65]
I have Ubiquiti Unifi UAP-AC-M-Pro network devices that are detected as Linux computers instead of network devices.

snmpget -v2c -c public "your AP IP" 1.3.6.1.2.1.1.2.0
snmpget returned: iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10

I modify your sysobject.ids to something like:
8072.3.2.10	UniFi	NETWORKING	UniFi AP

Is there another solution? Thanks

**Comment by g-bougard** [comment]
Hi @danielcousosouto 
this is a wrong solution as this sysobjectid is shared with a lot of other linux appliances.
A better solution would be to update the LinuxAppliance MibSupport plugin... but only if you're still using the latest v2.6 agent as Unifi devices has been added in that version.
See: [#823](https://github.com/fusioninventory/fusioninventory-agent/issues/823) and [#856](https://github.com/fusioninventory/fusioninventory-agent/issues/856)
So, what agent version are you using ?

**Comment by danielcousosouto** [comment]
Hello, I have updated Fusion and it already works correctly.

Thank you very much! @g-bougard
