### ISSUE TITLE
Konica Minolta

### ISSUE THREAD

**Issue by TheRoby** [fusioninventory/sysobject.ids#66]
Hi :)

I have some Konica Minolta Printers in my network. 2 was know, but the others not :)

55c-6e 
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.2.1.2.1.103.2.5
[55c-6e.txt](https://github.com/fusioninventory/sysobject.ids/files/5963967/55c-6e.txt)
224e 
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.112.3.2
[bh224e.txt](https://github.com/fusioninventory/sysobject.ids/files/5963968/bh224e.txt)
C224e
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.107.2.2
[c224e.txt](https://github.com/fusioninventory/sysobject.ids/files/5963969/c224e.txt)
C227
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.133.2.9
[c227.txt](https://github.com/fusioninventory/sysobject.ids/files/5963970/c227.txt)
C250i
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.181.2.1
[c250i.txt](https://github.com/fusioninventory/sysobject.ids/files/5963972/c250i.txt)
C454e
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.104.3.2
[c454e.txt](https://github.com/fusioninventory/sysobject.ids/files/5963973/c454e.txt)
C654e
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.80.3.6
[c654e.txt](https://github.com/fusioninventory/sysobject.ids/files/5963974/c654e.txt)
C3320i
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.184.2.1
[c3320i.txt](https://github.com/fusioninventory/sysobject.ids/files/5963976/c3320i.txt)
C3850
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.18334.1.1.1.2.1.113.2.5
[c3850.txt](https://github.com/fusioninventory/sysobject.ids/files/5963977/c3850.txt)

I think to update the file like this :
```
18334.1.2.1.2.1.103.2.5	Konica	PRINTER	55C-6E
18334.1.1.1.2.1.112.3.2	Konica	PRINTER	bizhub 224e
18334.1.1.1.2.1.107.2.2	Konica	PRINTER	bizhub C224e
18334.1.1.1.2.1.133.2.9	Konica	PRINTER	bizhub C227
18334.1.1.1.2.1.181.2.1	Konica	PRINTER	bizhub C250i
18334.1.1.1.2.1.104.3.2	Konica	PRINTER	bizhub C454e
18334.1.1.1.2.1.80.3.6	Konica	PRINTER	bizhub C654e
18334.1.1.1.2.1.184.2.1	Konica	PRINTER	bizhub C3320i
18334.1.1.1.2.1.113.2.5	Konica	PRINTER	bizhub C3850
```

I have right ?
Thank you

**Comment by g-bougard** [comment]
Of course you have right.
Thank you for sharing.
